site_name: StepUp Core
repo_url: https://github.com/reproducible-reporting/stepup-core
site_url: https://reproducible-reporting.github.io/stepup-core/
edit_uri: edit/main/docs/
site_description: StepUp Core Documentation
site_author: Toon Verstraelen
copyright: 2024-2025, Toon Verstraelen

watch:
  - stepup

strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn

extra:
  version:
    provider: mike
    alias: true
    default: stable

theme:
  name: material
  custom_dir: overrides
  font:
    text: IBM Plex Sans
    code: Source Code Pro
  features:
  - search.highlight
  - search.suggest
  - search.share
  - navigation.instant
  - navigation.instant.prefetch
  - content.code.copy
  - content.action.edit
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference

nav:
  - Home: index.md
  - installation.md
  - Getting Started:
    - getting_started/introduction.md
    - getting_started/first_step.md
    - getting_started/first_runpy.md
    - getting_started/dependencies.md
    - getting_started/static_files.md
    - getting_started/copy_mkdir.md
    - getting_started/workdir.md
    - getting_started/static_glob.md
    - getting_started/static_glob_conditional.md
    - getting_started/interactive_usage.md
    - getting_started/failing_steps.md
    - getting_started/call.md
    - getting_started/script_single.md
    - getting_started/script_multiple.md
    - getting_started/no_rules.md
    - getting_started/distributed_plans.md
    - getting_started/load_namespace.md
    - getting_started/automatic_cleaning.md
  - Advanced Topics:
    - advanced_topics/introduction.md
    - advanced_topics/static_named_glob.md
    - advanced_topics/static_deferred_glob.md
    - advanced_topics/optional_steps.md
    - advanced_topics/blocked_steps.md
    - advanced_topics/pools.md
    - advanced_topics/environment_variables.md
    - advanced_topics/volatile_outputs.md
    - advanced_topics/amending_steps.md
    - advanced_topics/variable_substitution.md
    - advanced_topics/here_and_root.md
    - advanced_topics/render_jinja.md
    - advanced_topics/cyclic_dependencies.md
    - advanced_topics/amending_static_inputs.md
    - advanced_topics/manual_cleaning.md
    - advanced_topics/stepup_root.md
    - advanced_topics/step_info.md
  - Reference:
    - reference/stepup.core.api.md
    - reference/stepup.core.call.md
    - reference/stepup.core.nglob.md
    - reference/stepup.core.script.md
    - reference/stepup.core.stepinfo.md
    - reference/interactive.md
    - reference/returncode.md
    - reference/environment_variables.md
  - Extending StepUp:
    - extending/introduction.md
    - extending/api.md
    - extending/action.md
    - extending/tool.md
  - changelog.md
  - development.md
  - license.md

exclude_docs: |
  */*/ch*/*.md
  */*/public/*.md

plugins:
- mike
- search:
    lang:
      - en
- macros:
    on_error_fail: true
    on_undefined: strict
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: ["stepup-core"]
        options:
          docstring_style: numpy
          show_root_heading: true
          docstring_section_style: list

markdown_extensions:
  - admonition
  - attr_list
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
